# Reshaping data

## Getting the data

Get the `SAFI_clean.csv` dataset, which you can read about and **download** from here: https://figshare.com/articles/SAFI_Survey_Results/6262019.

```{r}    
## load the tidyverse
library(tidyverse)

interviews <- read_csv("SAFI_clean.csv", na = "NULL")

## inspect the data
interviews

## preview the data
View(interviews)

attach(interviews)

interviews <- separate_rows(interviews, items_owned,sep= ";")

View(interviews)

unique_item <- unique(interviews["items_owned"])
test <- spread(data = interviews,items_owned, items_owned)
view(test)
new_table <- cbind(test$key_ID,!is.na(test[,15:31]))
new_table
```



## Splitting cells

Some columns in this dataset contain multiple pieces of information. For example, the `items_owned` column contains information about whether our respondents owned a fridge, a television, etc.  

This task involves splitting that into multiple values, and then creating new variables that are logical, in wide format to indicate for each interviewee whether they owned this item or not.

Hint: Try `separate_rows()`.  


Hint: To create the logical value that will "spread", you should create a new variable that is a constant logical type that will be spread as different item variables.

## Other methods

What could you have done with `strsplit()` as demonstrated in class, and how would this have helped? (Or made things more difficult?)
